aa/config/routes.rb
Rails.application.routes.draw do
	
  get 'users/index'
  get 'articles/index'
  get 'users/index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :articles
  resources :users
	  

  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

aa/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

aa/app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true, length: {minimum: 5}
	validates :text, presence: true


				 
end

aa/app/models/comment.rb
class Comment < ApplicationRecord
end

aa/app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: {maximum: 10}
	validates :email, presence:true, length: {maximum: 15}, uniqueness: {case_sensitive: false}

		has_secure_password
end

aa/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

aa/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
        @articles = Article.all
  end

  def new
      @article = Article.new
  end

  def create
     # render plain: params[:article].inspect
     @article = Article.new(article_params)
     if @article.save
      redirect_to @article
     else
      render 'new'
     end
  end

  
  def edit
    @article = Article.find(params[:id])
  end

  def show
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private 
    def article_params
      params.require(:article).permit(:title, :text)
    end

end

aa/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if(user && user.authenticate(params[:session][:password]))
  		log_in user
  		redirect_to articles_path
  	else
  		flash.now[:danger] = "Invalid credentials"
  		render 'new'
  	end

  end

  def destroy
  	log_out
  	redirect_to root_url
  end

end

aa/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	  	@user = User.new

  end

  def show
  	@user = User.find(params[:id]) 
  end

  def new
  	@user = User.new
  end

  def create
  @user = User.new(user_params)
  	if @user.save
      flash[:success] = "Account Created"
  		log_in @user
      redirect_to @user
  	else
      flash[:fail] = "Process aborted"
  		render 'index'
  	end

  end

  private
  def user_params
  	params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

end

aa/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

aa/app/helpers/application_helper.rb
module ApplicationHelper
end

aa/app/helpers/articles_helper.rb
module ArticlesHelper
end

aa/app/helpers/sessions_helper.rb
module SessionsHelper
	
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		if(session[:user_id])
			@current_user ||= User.find_by(id: session[:user_id])
		end
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end


end

aa/app/helpers/user_helper.rb
module UserHelper
end

aa/app/helpers/users_helper.rb
module UsersHelper
end

aa/app/helpers/welcome_helper.rb
module WelcomeHelper
end

aa/app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

aa/app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_with(model: @article, local: true) do |form| %>
	<% if @article.errors.any? %>
		<div id = "errors_explanation">
			<h2>
				<%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved.
			</h2>
			<ul>
				<% @article.errors.full_messages.each do |msg| %>
				<li><%= msg %> </li>
				<% end %>
			</ul>
			
		</div>
	<% end %>

<p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', articles_path %>

aa/app/views/articles/index.html.erb
<h1>Listing articles</h1>
 
 <%= link_to 'New article', new_article_path %>
 <br><br>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Delete',article_path(article), method: :delete, data: {confirm: 'Are you sure ?'} %></td>


    </tr>
  <% end %>
</table>

aa/app/views/articles/new.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |form| %>

	<% if @article.errors.any? %>
		<div id= "error_explanation">
		<h2>
			<%= pluralize(@article.errors.count,"error")%>
			prohibited this article from being saved:
		</h2>

		<ul>
			<% @article.errors.full_messages.each do |msg|%>
			<li><%= msg %></li>
			<% end %>
		</ul>
	
		</div>
	<% end %>

<p>
	<%= form.label :title %>
	<br>
	<%= form.text_field :title %>
</p>

<p>
	<%= form.label :text %>
	<br>
	<%= form.text_area :text %>
</p>

<p>
	<%= form.submit %>
</p>

<% end %>
<%= link_to 'Back', articles_path %>

aa/app/views/articles/show.html.erb
	<p>
		<strong>Title:</strong>
		<%= @article.title %>
	</p>

	<p>
		<strong>Text:</strong>
		<%= @article.text %>	
	</p>
<%= link_to 'Show', article_path(@article) %>
<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Show all', articles_path %>

aa/app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

aa/app/views/layouts/_header.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Box8", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
       
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %> <%= current_user.name %>  </li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

aa/app/views/layouts/_shim.html.erb
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>

aa/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <%= render 'layouts/shim' %>

  </head>

  <body>
  	    <%= render 'layouts/header' %>
  	<div class = "container">
  		<% flash.each do |message_type, message| %>
  		<div class = "alert">
  			 <%= message_type%> <%= message %>
  		</div>
  		<% end %>
  		    <%= yield %>
  		<%= debug(params) if Rails.env.development? %>

  	</div>
  </body>
</html>

aa/app/views/shared/_error_message.html.erb
<% if @user.errors.any? %>
<div id = error_explanation>
	The form contains <%= pluralize(@user.errors.count, "error")%>.	
</div>
<ul>
	<% @user.errors.full_messages.each do |msg| %>
	<li>
		<%= msg %>
	</li>
	<% end %>
</ul>
<% end %>

aa/app/views/users/index.html.erb
<%= form_with scope: :user, url: users_path, local: true do |form| %>
<%=  render 'shared/error_message' %>


<%= form.label :name %>
<%= form.text_field :name, class: 'form-control' %> <br>

<%= form.label :email %>
<%= form.email_field :email, class: 'form-control' %> <br>

<%= form.label :password %>
<%= form.password_field :password, class: 'form-control' %> <br>

<%= form.label :confirm_password %>
<%= form.password_field :cofirm_password, class: 'form-control' %> <br>

<%= form.submit "Create my account", class: 'btn btn-info' %>


 <% end %>

aa/app/views/users/show.html.erb
<%= @user.name %> <br>
<%= @user.email %>
<div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Dropdown Example
    <span class="caret"></span></button>
    <ul class="dropdown-menu">
      <li><a href="#">HTML</a></li>
      <li><a href="#">CSS</a></li>
      <li><a href="#">JavaScript</a></li>
    </ul>
  </div>

aa/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>